# Lock Test Recipe for zipget-rs
# Tests --lock parameter and SHA verification functionality

[lock-test-http]
url = "https://thetestdata.com/samplefiles/zip/Thetestdata_ZIP_10KB.zip"
unzip_to = "./test-output/lock-http"
save_as = "./test-downloads/lock-http.zip"

[lock-test-github]
github = { repo = "vivainio/unxml-rs", tag = "v0.1.1" }
unzip_to = "./test-output/lock-github"
save_as = "./test-downloads/lock-github.zip"
